const languages = {
  'None': 'text',
  'HTML': 'html',
  'XML': 'xml',
  'C#': 'cs',
  'CSS': 'css',
  'JavaScript': 'js',
  'JavaScript React': 'jsx',
  'Arduino': 'arduino',
  'ASP.NET': 'aspnet',
  'AutoIt': 'autoit',
  'Bash': 'bash',
  'Batch': 'batch',
  'C': 'c',
  'C++': 'cpp',
  'Clojure': 'clojure',
  'cmake': 'cmake',
  'D': 'd',
  'Dart': 'dart',
  'Diff': 'diff',
  'EJS': 'ejs',
  'F#': 'fsharp',
  'Git': 'git',
  'Go': 'go',
  'Haskell': 'hs',
  'Http': 'http',
  'INI': 'ini',
  'Java': 'java',
  'JSON': 'json',
  'Kotlin': 'kt',
  'Less': 'less',
  'Lua': 'lua',
  'Makefile': 'makefile',
  'Markdown': 'md',
  'Objective C': 'objc',
  'Pascal': 'pascal',
  'Perl': 'perl',
  'PHP': 'php',
  'Powershell': 'powershell',
  'Pug': 'pug',
  'Q#': 'qs',
  'QML': 'qml',
  'Python': 'py',
  'R': 'r',
  'Razor C#': 'cshtml',
  'Ruby': 'rb',
  'Solution': 'sln',
  'SQL': 'sql',
  'TOML': 'toml',
  'TypeScript': 'ts',
  'TypeScript React': 'tsx',
  'V': 'v',
  'VB.NET': 'vbnet',
  'Vim': 'vim',
  'Visual Basic': 'vb',
  'WebAssembly': 'wasm',
  'YAML': 'yml'
};

export default languages;